<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
    <?php include('./template/header.phtml'); ?>

    <form action="?page=addproduct" method="post" enctype="multipart/form-data">
        <label for="image">image du produit :</label>
        <input type="file" id="image" name="image">
        <br>
        <label for="name">Nom du produit :</label>
        <input type="text" id="name" name="name" required>
        <br>
        <label for="description">Description:</label>
        <textarea id="description" name="description" required></textarea>
        <br>
        <label for="price">Prix:</label>
        <input type="number" id="price" name="price" step="0.01" required>
        <button type="submit" value="Ajouter le produit">Ajouter le produit</button>
    </form>

    <?php include('./template/footer.phtml'); ?>
</body>
</html>
