<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <title>Supprimer un produit</title>
</head>
<body>
    <?php include('./template/header.phtml'); ?>

    <form action="?page=deleteproduct" method="post">
        <label for="product">Sélectionnez un produit à supprimer:</label>
            <select name="product_id" id="product" required>
                <option value="">Sélectionnez un produit à supprimer</option>
                <?php foreach ($products as $product): ?>
                    <option value="<?= $product['id'] ?>" data-image="<?= $product['image'] ?>" data-name="<?= $product['name'] ?>" data-description="<?= $product['description'] ?>" data-price="<?= $product['price'] ?>"><?= $product['name'] ?></option>
                <?php endforeach; ?>
            </select>
            <button type="submit" value="Supprimer le produit">Supprimer le produit</button>
    </form>
</body>
</html>