<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="./assets/css/style.css">
    <title>Modifier un produit</title>
</head>
<body>
    <?php include('./template/header.phtml'); ?>

    <form action="?page=updateproduct" method="post" enctype="multipart/form-data">
        <label for="product">Sélectionnez un produit à modifier:</label>
        <select name="product_id" id="product" required>
            <option value="">Sélectionnez un produit à modifier</option>
            <?php foreach ($products as $product): ?>
                <option value="<?= $product['id'] ?>" data-image="<?= $product['image'] ?>" data-name="<?= $product['name'] ?>" data-description="<?= $product['description'] ?>" data-price="<?= $product['price'] ?>"><?= $product['name'] ?></option>
            <?php endforeach; ?>
        </select>
        <br><br>

        <label for="image">image du produit :</label>
        <input type="file" id="image" name="image">
        <br>
        <label for="name">Nom du produit :</label>
        <input type="text" id="name" name="name" required>
        <br>
        <label for="description">Description:</label>
        <textarea id="description" name="description" required></textarea>
        <br>
        <label for="price">Prix:</label>
        <input type="number" id="price" name="price" step="0.01" required>
        <button type="submit" value="Modifier le produit">Modifier le produit</button>
    </form>

    <script src="./assets/js/script.js"></script>
    <?php include('./template/footer.phtml'); ?>
</body>
</html>
